version: '3.8'

services:
  db_postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: mi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db_postgres
    volumes:
      - .:/app
      - ./usuario1:/home/usuario1
      - ./backups:/backups
    environment:
      - PYTHONUNBUFFERED=1
    command: tail -f /dev/null

